### ISSUE TITLE
[feature] [codeblocks] codeblock files?

### ISSUE THREAD

**Issue by Merith-TK** [12944qwerty/replugged-plugins#1]
Basically just use file extension (if its an supported codeblock file, since typically the \`\`\`tag is the same as the file extension for that file type)
![image](https://github.com/12944qwerty/replugged-plugins/assets/10422110/fae13840-13ce-4e61-a35e-9f93c49dc499)

**Comment by 12944qwerty** [comment]
So this is weirdly much more difficult to implement (I had tried when this pr was opened). Sorry for the late reply.
I don't think I'll end up doing this ever because it is a file that has a completely different approach to rendering.
